# Generated by Django 6.0 on 2026-01-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_yearlyplan_monthlyplan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyplan',
            new_name='api_monthly_user_id_f03205_idx',
            old_name='api_monthlyplan_user_id_year_month_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='api_task_user_id_807a40_idx',
            old_name='api_task_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='api_task_user_id_5e79a6_idx',
            old_name='api_task_user_id_completed_idx',
        ),
        migrations.RenameIndex(
            model_name='yearlyplan',
            new_name='api_yearlyp_user_id_2c1063_idx',
            old_name='api_yearlyplan_user_id_year_idx',
        ),
    ]
