# Generated by Django 6.0 on 2026-01-18 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_api_monthlyplan_user_id_year_month_idx_api_monthly_user_id_f03205_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekdays', 'Weekdays')], default='once', max_length=10),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'is_template'], name='api_task_user_id_239fd1_idx'),
        ),
    ]
