# Generated by Cursor on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_task_is_template_task_recurrence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="scheduled_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]

