# Generated by Django 6.0 on 2026-01-21 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_scheduled_time_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('fat_loss', 'Fat loss'), ('maintenance', 'Maintenance'), ('recomp', 'Recomposition'), ('lean_bulk', 'Lean bulk'), ('bulk', 'Bulk')], default='maintenance', max_length=12)),
                ('calorie_adjustment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein_g_per_kg', models.DecimalField(decimal_places=2, default=1.8, max_digits=4)),
                ('fat_g_per_kg', models.DecimalField(decimal_places=2, default=0.8, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little/no exercise)'), ('light', 'Light (1-3 days/week)'), ('moderate', 'Moderate (3-5 days/week)'), ('active', 'Active (6-7 days/week)'), ('athlete', 'Athlete (very intense / 2x per day)'), ('custom', 'Custom multiplier')], default='moderate', max_length=12)),
                ('activity_multiplier', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMacroTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.PositiveIntegerField()),
                ('carbs_g', models.PositiveIntegerField()),
                ('fat_g', models.PositiveIntegerField()),
                ('bmr', models.PositiveIntegerField()),
                ('tdee', models.PositiveIntegerField()),
                ('algorithm_version', models.CharField(default='mifflin_v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_macro_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='api_dailyma_user_id_e5961b_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
