# Generated by Django 6.0 on 2026-01-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_nutritiongoal_nutritionprofile_dailymacrotarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories_kcal', models.PositiveIntegerField()),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='api.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['user', 'name'], name='api_foodite_user_id_c7d012_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlogentry',
            index=models.Index(fields=['user', 'date'], name='api_foodlog_user_id_a535b0_idx'),
        ),
    ]
