# Generated by Django 6.0 on 2026-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_weightcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency_per_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='specific_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekdays', 'Weekdays'), ('specific_days', 'Specific Days')], default='once', max_length=15),
        ),
    ]
